version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: lol_db_container
    restart: always

    # 데이터베이스 설정 (환경 변수)
    environment:
      MYSQL_DATABASE: lol_esports_analysis
      MYSQL_USER: nar_id
      MYSQL_PASSWORD: nar_pw
      MYSQL_ROOT_PASSWORD: root_password
      TZ: Asia/Seoul

    # 포트 매핑 (내 컴퓨터:컨테이너)
    ports:
      - "3308:3306"

    # MySQL 서버 설정
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    # 데이터 영속성을 위한 볼륨 설정
    volumes:
      - db_data:/var/lib/mysql

# 도커 볼륨 정의
volumes:
  db_data: