spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        jdbc:
          batch_size: 50
          order_inserts: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true

notification:
  enabled: true
  slack:
    webhook-url: ${SLACK_WEBHOOK_URL}

# 로깅 관련 공통 설정
logging:
  level:
    org.hibernate.SQL: info

google:
  drive:
    csv-file-id: "1v6LRphp2kYciU4SXp0PCjEMuev1bDejc"
