spring:
  profiles:
    active: prod

  jpa:
    properties:
      hibernate:
        format_sql: false
        # 배치 설정 (공통으로 사용)
        jdbc:
          batch_size: 50
          order_inserts: true
    # N+1 문제 방지를 위한 공통 설정
    open-in-view: false
